# NAME: Yanyin Liu
# EMAIL: yanyinliu8@gmail.com
# ID: 604952257
FILES = lab1a.c Makefile README

default:
	@gcc -g -Wall -Wextra lab1a.c -o lab1a

clean:
	@rm -f lab1a *.tar.gz

dist:
	@tar -czf lab1a-604952257.tar.gz $(FILES)

