#NAME: Shawye Ho,Yanyin Liu


#generic Makefile

all: lab3b.py
	ln -s lab3b.py lab3b
	chmod +x lab3b

clean:
	$(RM) lab3b lab3b-704839317.tar.gz

dist:
	tar -zcvf lab3b-704839317.tar.gz lab3b.py Makefile README 
